% -------------------------------------------------------------------
%  Generated by MATLAB on 2-Dec-2024 15:37:03
%  MATLAB version: 23.2.0.2668659 (R2023b) Update 9
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

Distancias = saveVarsMat.Distancias; % <32x32 double> too many elements

Hijos_Crossover = 2;

Num_Competidores = 5;

Num_Gen = 200;

Num_Pob = 100;

Num_iteraciones = 10;

Pm = 0.2;

Resultados_GridSearch = saveVarsMat.Resultados_GridSearch; % <1x1 table> unsupported class

ans = saveVarsMat.ans; % <1x1 parallel.ProcessPool> unsupported class

c = 486;

combinations = saveVarsMat.combinations; % <6x486 double> too many elements

data = saveVarsMat.data; % <32x33 double> too many elements

desviacion = 130.52950711044866;

m = 5;

media = 8924.7031753164;

mejor = 8820.033246008792;

num_combinations = 486;

param_ranges = cell(6, 2);
param_ranges{1,1} = 'Num_Pob';
param_ranges{2,1} = 'Num_Gen';
param_ranges{3,1} = 'Pm';
param_ranges{4,1} = 'm';
param_ranges{5,1} = 'Num_Competidores';
param_ranges{6,1} = 'Hijos_Crossover';
param_ranges{1,2} = [20 50 100];
param_ranges{2,2} = [50 100 200];
param_ranges{3,2} = [0.05 0.1 0.2];
param_ranges{4,2} = [2 3 5];
param_ranges{5,2} = [2 3 5];
param_ranges{6,2} = [1 2];

params = [100; 200; 0.2; 5; 5; 2];

peor = 9217.5820927642962;

tiempo = 63.5693426;

clear saveVarsMat;
